import { applyKey, isCorrectTyped, type Key } from './checkAnswer'
import type { AnswerRecord, Question } from './types'

/**
 * The rules of a round, as a pure function: given the current state and something the player
 * did, return the next state. Keeping this free of timers and randomness makes it easy to test.
 * The next question is generated by the caller and passed in with each action.
 */

export interface Feedback {
  kind: 'correct' | 'wrong' | 'skip'
  /** Increments every time, so the same animation can replay back-to-back. */
  seq: number
}

export interface SprintState {
  question: Question
  input: string
  records: AnswerRecord[]
  questionStartedAt: number
  feedback: Feedback | null
}

export type SprintAction =
  | { type: 'start'; now: number }
  | { type: 'key'; key: Key; now: number; next: Question }
  | { type: 'choose'; value: number; now: number; next: Question }
  | { type: 'skip'; now: number; next: Question }

export function initialSprintState(first: Question): SprintState {
  return { question: first, input: '', records: [], questionStartedAt: 0, feedback: null }
}

function advance(
  state: SprintState,
  record: Omit<AnswerRecord, 'question' | 'ms'>,
  now: number,
  next: Question,
  kind: Feedback['kind'],
): SprintState {
  return {
    question: next,
    input: '',
    records: [...state.records, { question: state.question, ms: now - state.questionStartedAt, ...record }],
    questionStartedAt: now,
    feedback: { kind, seq: (state.feedback?.seq ?? 0) + 1 },
  }
}

export function sprintReducer(state: SprintState, action: SprintAction): SprintState {
  switch (action.type) {
    case 'start':
      return { ...state, questionStartedAt: action.now }

    case 'key': {
      if (state.question.input !== 'type') return state
      const input = applyKey(state.input, action.key)
      // Zetamac-style: the moment the typed value is right, move on. No Enter key needed.
      if (isCorrectTyped(input, state.question.answer)) {
        return advance(state, { correct: true, skipped: false }, action.now, action.next, 'correct')
      }
      return { ...state, input }
    }

    case 'choose': {
      if (state.question.input !== 'choice') return state
      // A wrong tap counts as a miss and moves on, so guessing never pays.
      const correct = Math.abs(action.value - state.question.answer) < 1e-9
      return advance(
        state,
        { correct, skipped: false, given: action.value },
        action.now,
        action.next,
        correct ? 'correct' : 'wrong',
      )
    }

    case 'skip':
      return advance(state, { correct: false, skipped: true }, action.now, action.next, 'skip')
  }
}

export interface RoundSummary {
  score: number
  attempted: number
  accuracy: number
  avgCorrectMs: number | null
}

export function summarize(records: AnswerRecord[]): RoundSummary {
  const correct = records.filter((r) => r.correct)
  return {
    score: records.reduce((s, r) => s + (r.points ?? (r.correct ? 1 : 0)), 0),
    attempted: records.length,
    accuracy: records.length ? correct.length / records.length : 0,
    avgCorrectMs: correct.length ? correct.reduce((s, r) => s + r.ms, 0) / correct.length : null,
  }
}
